version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.9'

python:
  install:
    - requirements: '{{cookiecutter.project_name}}/docs/requirements.txt'

sphinx:
  configuration: '{{cookiecutter.project_name}}/docs/conf.py'
  fail_on_warning: true
