# Docs:
# https://docs.readthedocs.io/en/stable/config-file/v2.html
# https://docs.readthedocs.io/en/stable/build-customization.html
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: '3.9'
  jobs:
    # See https://github.com/readthedocs/readthedocs.org/issues/4912
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - |
        cd '{{cookiecutter.project_name}}'
        && source "$(dirname "$(which python)")/activate"
        && poetry install -E docs --no-dev --remove-untracked

sphinx:
  configuration: '{{cookiecutter.project_name}}/docs/conf.py'
  fail_on_warning: true
