version: 2

build:
  os: ubuntu-20.04
  tools:
    python: '3.9'

python:
  install:
    - method: pip
      path: '\{\{cookiecutter.project_name\}\}'
      extra_requirements:
        - docs

sphinx:
  configuration: '{{cookiecutter.project_name}}/docs/conf.py'
  fail_on_warning: true
