environment:
  matrix:
    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

init:
  - "%PYTHON%/python -V"
  - "%PYTHON%/python -c \"import struct;print( 8 * struct.calcsize(\'P\'))\""

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
