name: docs

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docs.yml'
      - 'tests/build_docs.sh'
      - '{{cookiecutter.project_name}}/docs/**/*'
      - '{{cookiecutter.project_name}}/pyproject.toml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install poetry
      run: |
        curl -sSL 'https://install.python-poetry.org' | python -

        # Adding `poetry` to `$PATH`:
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Install dependencies
      run: poetry install

    - name: Build docs
      run: poetry run bash tests/build_docs.sh

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      if: github.event_name == 'push'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages  # The branch the action should deploy to.
        folder: html  # The folder the action should deploy.
        clean: true  # Automatically remove deleted files from the deploy branch
