name: hadolint

on:
  push:
    branches:
      - master
    paths:
      - '{{cookiecutter.project_name}}/docker/django/Dockerfile'
  pull_request:
    paths:
      - '{{cookiecutter.project_name}}/docker/django/Dockerfile'
  workflow_dispatch:

concurrency: 
  group: hadolint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: '{{cookiecutter.project_name}}/docker/django/Dockerfile'
          failure-threshold: style
