name: hadolint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: '{{cookiecutter.project_name}}/docker/django/Dockerfile'
          failure-threshold: style
