name: shellcheck

on:
  push:
    branches:
      - master
    paths:
      - 'tests/**/*.sh'
      - '{{cookiecutter.project_name}}/**/*.sh'
      - '.github/workflows/shellcheck.yml'
  pull_request:
    paths:
      - 'tests/**/*.sh'
      - '{{cookiecutter.project_name}}/**/*.sh'
      - '.github/workflows/shellcheck.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: --shell bash
        with:
          severity: style
          check_together: 'yes'
