name: shellcheck

on:
  push:
    branches:
      - master
    paths:
      - 'tests/**/*.sh'
      - '{{cookiecutter.project_name}}/**/*.sh'
  pull_request:
    paths:
      - 'tests/**/*.sh'
      - '{{cookiecutter.project_name}}/**/*.sh'
  workflow_dispatch:

concurrency:
  group: shellcheck-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
        env:
          SHELLCHECK_OPTS: -s bash
        with:
          severity: style
          check_together: 'yes'
